# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp/llmsdk.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nlp.test1 import test1_pb2 as nlp_dot_test1_dot_test1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nlp/llmsdk.proto\x12\nnlp.llmsdk\x1a\x15nlp/test1/test1.proto\"\x07\n\x05\x45mpty\"\x12\n\x10ReportListObject2I\n\x0eHandlerService\x12\x37\n\nAddInbound\x12\x14.nlp.test1.MyStruct1\x1a\x11.nlp.llmsdk.Empty\"\x00\x42\x16Z\x14\x62ogoo.com/nlp/llmsdkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp.llmsdk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024bogoo.com/nlp/llmsdk'
  _globals['_EMPTY']._serialized_start=55
  _globals['_EMPTY']._serialized_end=62
  _globals['_REPORTLISTOBJECT']._serialized_start=64
  _globals['_REPORTLISTOBJECT']._serialized_end=82
  _globals['_HANDLERSERVICE']._serialized_start=84
  _globals['_HANDLERSERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
