# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from user_center import user_center_pb2 as user__center_dot_user__center__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_center/user_center_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserCenterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewCaptcha = channel.unary_unary(
                '/user_center.UserCenterService/NewCaptcha',
                request_serializer=user__center_dot_user__center__pb2.Empty.SerializeToString,
                response_deserializer=user__center_dot_user__center__pb2.NewCaptchaResponse.FromString,
                _registered_method=True)
        self.UserRegistry = channel.unary_unary(
                '/user_center.UserCenterService/UserRegistry',
                request_serializer=user__center_dot_user__center__pb2.UserRegistryRequest.SerializeToString,
                response_deserializer=user__center_dot_user__center__pb2.UserRegistryResponse.FromString,
                _registered_method=True)
        self.UserLogin = channel.unary_unary(
                '/user_center.UserCenterService/UserLogin',
                request_serializer=user__center_dot_user__center__pb2.UserLoginRequest.SerializeToString,
                response_deserializer=user__center_dot_user__center__pb2.UserLoginResponse.FromString,
                _registered_method=True)
        self.UpdateToken = channel.unary_unary(
                '/user_center.UserCenterService/UpdateToken',
                request_serializer=user__center_dot_user__center__pb2.Empty.SerializeToString,
                response_deserializer=user__center_dot_user__center__pb2.UpdateTokenResponse.FromString,
                _registered_method=True)
        self.NewJWKS = channel.unary_unary(
                '/user_center.UserCenterService/NewJWKS',
                request_serializer=user__center_dot_user__center__pb2.NewJWKSRequest.SerializeToString,
                response_deserializer=user__center_dot_user__center__pb2.NewJWKSResponse.FromString,
                _registered_method=True)


class UserCenterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewCaptcha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewJWKS(self, request, context):
        """生成新的JWKS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCenterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewCaptcha': grpc.unary_unary_rpc_method_handler(
                    servicer.NewCaptcha,
                    request_deserializer=user__center_dot_user__center__pb2.Empty.FromString,
                    response_serializer=user__center_dot_user__center__pb2.NewCaptchaResponse.SerializeToString,
            ),
            'UserRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRegistry,
                    request_deserializer=user__center_dot_user__center__pb2.UserRegistryRequest.FromString,
                    response_serializer=user__center_dot_user__center__pb2.UserRegistryResponse.SerializeToString,
            ),
            'UserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLogin,
                    request_deserializer=user__center_dot_user__center__pb2.UserLoginRequest.FromString,
                    response_serializer=user__center_dot_user__center__pb2.UserLoginResponse.SerializeToString,
            ),
            'UpdateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateToken,
                    request_deserializer=user__center_dot_user__center__pb2.Empty.FromString,
                    response_serializer=user__center_dot_user__center__pb2.UpdateTokenResponse.SerializeToString,
            ),
            'NewJWKS': grpc.unary_unary_rpc_method_handler(
                    servicer.NewJWKS,
                    request_deserializer=user__center_dot_user__center__pb2.NewJWKSRequest.FromString,
                    response_serializer=user__center_dot_user__center__pb2.NewJWKSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_center.UserCenterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_center.UserCenterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserCenterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewCaptcha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_center.UserCenterService/NewCaptcha',
            user__center_dot_user__center__pb2.Empty.SerializeToString,
            user__center_dot_user__center__pb2.NewCaptchaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_center.UserCenterService/UserRegistry',
            user__center_dot_user__center__pb2.UserRegistryRequest.SerializeToString,
            user__center_dot_user__center__pb2.UserRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_center.UserCenterService/UserLogin',
            user__center_dot_user__center__pb2.UserLoginRequest.SerializeToString,
            user__center_dot_user__center__pb2.UserLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_center.UserCenterService/UpdateToken',
            user__center_dot_user__center__pb2.Empty.SerializeToString,
            user__center_dot_user__center__pb2.UpdateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewJWKS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_center.UserCenterService/NewJWKS',
            user__center_dot_user__center__pb2.NewJWKSRequest.SerializeToString,
            user__center_dot_user__center__pb2.NewJWKSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
